/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'bootloader'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 1 */
struct __attribute__((packed)) __attribute__((aligned(2))) gdt
{
  __int16 limit;
  __int64 base;
};

